version: '3.1'

services:

  flyboydb:
    image: mongo
    container_name: iflyboylog_database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./flyboydb:/data/db
    networks:
      - flyboylog_network # Specify the network for the 'mongo' service

  iflyboylog:
    container_name: iflyboylog
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - flyboydb
    networks:
      - flyboylog_network # Specify the network for the 'iflyboylog' service
volumes:
  flyboydb: {}
networks:
  flyboylog_network:
    driver: bridge
