Version: '3.1'

services:

  mongo:
    image: mongo
    container_name: database 
    restart: always
    ports:
      - 27017:27017
    # volumes:
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root 